### PR TITLE
Immutable

### PR DESCRIPTION
**Pull request by dweedon**

### CODE REVIEW

**Comment by terribleplan** [comment]
It is actually looking like es6 proxies *are* impossible to implement with babel or babel-polyfill, at least in the case you don't know what attributes will be proxying in advance, so we may have to rethink how this works... (the current failure in travis is due to the version of chromium travis has not having support for proxies)

**Comment by terribleplan** [comment]
Non-working environments are:
* Safari (desktop & iOS) < 10 (10 is current)
* Android < 5 (6 is current)
* IE (works in Edge)
* Phantom
* Konqueror
* Some other weird mobile browsers

Immaterial:
* Firefox < 18 (50 is current)
* Node <= 4 (6/7 is current)
* Chrome < 49 (55 is current)
* Opera < 36 (42 is current)

**Comment by dweedon** [comment]
I'd say forget about it then. There syntax actually looks pretty clean without it, and it's probably actually more clear what is going on.

**Comment by dweedon** [comment]
Green now.

**Pull request merged**
